# Generated by Django 4.0.10 on 2024-01-30 02:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(6)])),
                ('password', models.CharField(max_length=30, validators=[django.core.validators.MinLengthValidator(6)])),
                ('displayName', models.CharField(max_length=30)),
            ],
        ),
    ]
