# Generated by Django 4.0.10 on 2024-01-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_user_displayname_user_display_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
