# Generated by Django 4.0.10 on 2024-01-31 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_user_display_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolist',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.DeleteModel(
            name='TodoList',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
